title: Semantic - Jekyll
description: A Jekyll Landing Page Theme
sitename: Your Website
baseurl: '/semantic-jekyll'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - sections
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME